source 'https://github.com/CocoaPods/Specs.git'

# inhibit_all_warnings!
use_frameworks!

platform :ios, '11.0'

target 'NumPadExample' do
        pod 'CommonKit', path: '..'
	pod 'PhoneNumberKit', git: 'https://github.com/oskarirauta/PhoneNumberKit.git'
end
