//
//  FontAwesome+regular.swift
//
//  Created by Oskari Rauta on 16/04/2018.
//  Copyright © 2018 Oskari Rauta. All rights reserved.
//

import Foundation

extension FontAwesome { // regular
    
    public enum regular: String, IconEnum {
        
        public static var fontType: Font { return .far }
        
        case addressBook = "address-book \u{f2b9}"
        case addressCard = "address-card \u{f2bb}"
        case arrowAltCircleDown = "arrow-alt-circle-down \u{f358}"
        case arrowAltCircleLeft = "arrow-alt-circle-left \u{f359}"
        case arrowAltCircleRight = "arrow-alt-circle-right \u{f35a}"
        case arrowAltCircleUp = "arrow-alt-circle-up \u{f35b}"
        case bell = "bell \u{f0f3}"
        case bellSlash = "bell-slash \u{f1f6}"
        case bookmark = "bookmark \u{f02e}"
        case building = "building \u{f1ad}"
        case calendar = "calendar \u{f133}"
        case calendarAlt = "calendar-alt \u{f073}"
        case calendarCheck = "calendar-check \u{f274}"
        case calendarMinus = "calendar-minus \u{f272}"
        case calendarPlus = "calendar-plus \u{f271}"
        case calendarTimes = "calendar-times \u{f273}"
        case caretSquareDown = "caret-square-down \u{f150}"
        case caretSquareLeft = "caret-square-left \u{f191}"
        case caretSquareRight = "caret-square-right \u{f152}"
        case caretSquareUp = "caret-square-up \u{f151}"
        case chartBar = "chart-bar \u{f080}"
        case checkCircle = "check-circle \u{f058}"
        case checkSquare = "check-square \u{f14a}"
        case circle = "circle \u{f111}"
        case clipboard = "clipboard \u{f328}"
        case clock = "clock \u{f017}"
        case clone = "clone \u{f24d}"
        case closedCaptioning = "closed-captioning \u{f20a}"
        case comment = "comment \u{f075}"
        case commentAlt = "comment-alt \u{f27a}"
        case comments = "comments \u{f086}"
        case compass = "compass \u{f14e}"
        case copy = "copy \u{f0c5}"
        case copyright = "copyright \u{f1f9}"
        case creditCard = "credit-card \u{f09d}"
        case dotCircle = "dot-circle \u{f192}"
        case edit = "edit \u{f044}"
        case envelope = "envelope \u{f0e0}"
        case envelopeOpen = "envelope-open \u{f2b6}"
        case eyeSlash = "eye-slash \u{f070}"
        case file = "file \u{f15b}"
        case fileAlt = "file-alt \u{f15c}"
        case fileArchive = "file-archive \u{f1c6}"
        case fileAudio = "file-audio \u{f1c7}"
        case fileCode = "file-code \u{f1c9}"
        case fileExcel = "file-excel \u{f1c3}"
        case fileImage = "file-image \u{f1c5}"
        case filePdf = "file-pdf \u{f1c1}"
        case filePowerpoint = "file-powerpoint \u{f1c4}"
        case fileVideo = "file-video \u{f1c8}"
        case fileWord = "file-word \u{f1c2}"
        case flag = "flag \u{f024}"
        case folder = "folder \u{f07b}"
        case folderOpen = "folder-open \u{f07c}"
        case frown = "frown \u{f119}"
        case futbol = "futbol \u{f1e3}"
        case gem = "gem \u{f3a5}"
        case handLizard = "hand-lizard \u{f258}"
        case handPaper = "hand-paper \u{f256}"
        case handPeace = "hand-peace \u{f25b}"
        case handPointDown = "hand-point-down \u{f0a7}"
        case handPointLeft = "hand-point-left \u{f0a5}"
        case handPointRight = "hand-point-right \u{f0a4}"
        case handPointUp = "hand-point-up \u{f0a6}"
        case handPointer = "hand-pointer \u{f25a}"
        case handRock = "hand-rock \u{f255}"
        case handScissors = "hand-scissors \u{f257}"
        case handSpock = "hand-spock \u{f259}"
        case handshake = "handshake \u{f2b5}"
        case hdd = "hdd \u{f0a0}"
        case heart = "heart \u{f004}"
        case hospital = "hospital \u{f0f8}"
        case hourglass = "hourglass \u{f254}"
        case idBadge = "id-badge \u{f2c1}"
        case idCard = "id-card \u{f2c2}"
        case image = "image \u{f03e}"
        case images = "images \u{f302}"
        case keyboard = "keyboard \u{f11c}"
        case lemon = "lemon \u{f094}"
        case lifeRing = "life-ring \u{f1cd}"
        case lightbulb = "lightbulb \u{f0eb}"
        case listAlt = "list-alt \u{f022}"
        case map = "map \u{f279}"
        case meh = "meh \u{f11a}"
        case minusSquare = "minus-square \u{f146}"
        case moneyBillAlt = "money-bill-alt \u{f3d1}"
        case moon = "moon \u{f186}"
        case newspaper = "newspaper \u{f1ea}"
        case objectGroup = "object-group \u{f247}"
        case objectUngroup = "object-ungroup \u{f248}"
        case paperPlane = "paper-plane \u{f1d8}"
        case pauseCircle = "pause-circle \u{f28b}"
        case playCircle = "play-circle \u{f144}"
        case plusSquare = "plus-square \u{f0fe}"
        case questionCircle = "question-circle \u{f059}"
        case registered = "registered \u{f25d}"
        case save = "save \u{f0c7}"
        case shareSquare = "share-square \u{f14d}"
        case smile = "smile \u{f118}"
        case snowflake = "snowflake \u{f2dc}"
        case square = "square \u{f0c8}"
        case star = "star \u{f005}"
        case starHalf = "star-half \u{f089}"
        case stickyNote = "sticky-note \u{f249}"
        case stopCircle = "stop-circle \u{f28d}"
        case sun = "sun \u{f185}"
        case thumbsDown = "thumbs-down \u{f165}"
        case thumbsUp = "thumbs-up \u{f164}"
        case timesCircle = "times-circle \u{f057}"
        case trashAlt = "trash-alt \u{f2ed}"
        case user = "user \u{f007}"
        case userCircle = "user-circle \u{f2bd}"
        case windowClose = "window-close \u{f410}"
        case windowMaximize = "window-maximize \u{f2d0}"
        case windowMinimize = "window-minimize \u{f2d1}"
        case windowRestore = "window-restore \u{f2d2}"
    }
}
