source 'https://github.com/CocoaPods/Specs.git'

# inhibit_all_warnings!
use_frameworks!

platform :ios, '11.0'

target 'DispatchExample' do
        pod 'CommonKit', git: 'https://github.com/oskarirauta/CommonKit.git'
end
